name: React with CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Install node_modules
        run: npm install
      - name: Build Project
        run: npm run build

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: |
         docker build -t react-docker:latest .
      - name: Tag Image
        run: |
          docker tag react-docker-project:latest ${{ secrets.DOCKER_USERNAME }}/react-docker-project:latest
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/react-docker-project:latest
      - name: success
        run: echo "Success CI CD Job"
